
import React, { useState, useMemo } from 'react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, 
  AreaChart, Area, PieChart, Pie
} from 'recharts';
import { Info, Zap, TrendingUp, Calendar, Clock, ArrowUpRight, PieChart as PieIcon, Activity } from 'lucide-react';

const RewardCalculator: React.FC = () => {
  const [stake, setStake] = useState(1200000);
  const [voters, setVoters] = useState(5000000);
  const [commission, setCommission] = useState(10);
  const [viewMode, setViewMode] = useState<'projections' | 'trends'>('projections');
  const [timeframe, setTimeframe] = useState<'daily' | 'monthly' | 'annual'>('annual');

  const stats = useMemo(() => {
    const BASE_APR = 0.06; // 6% base APR for the network
    
    // Logic: 
    // 1. Delegate gets 100% of rewards from their own stake.
    // 2. Delegate gets 'commission' % of rewards generated by their voters.
    const voterAnnualRewards = voters * BASE_APR;
    const commissionRevenue = voterAnnualRewards * (commission / 100);
    const selfStakeRevenue = stake * BASE_APR;
    const totalAnnual = commissionRevenue + selfStakeRevenue;
    
    return {
      annual: totalAnnual,
      monthly: totalAnnual / 12,
      weekly: totalAnnual / 52,
      daily: totalAnnual / 365,
      commissionShare: commissionRevenue,
      selfShare: selfStakeRevenue,
      voterYield: BASE_APR * (1 - (commission / 100)) * 100
    };
  }, [stake, voters, commission]);

  // Forecast data for Area Chart (Cumulative over 12 months)
  const forecastData = useMemo(() => {
    return Array.from({ length: 13 }, (_, i) => ({
      month: `M${i}`,
      cumulative: Math.round(stats.monthly * i),
      monthly: Math.round(stats.monthly)
    }));
  }, [stats]);

  // Mock historical network APY trends
  const trendData = [
    { date: 'Jan', apy: 6.2 },
    { date: 'Feb', apy: 6.0 },
    { date: 'Mar', apy: 6.5 },
    { date: 'Apr', apy: 6.3 },
    { date: 'May', i: 5.9 },
    { date: 'Jun', apy: 6.1 },
    { date: 'Jul', apy: 6.4 },
  ];

  const breakdownData = [
    { name: 'Commission', value: stats.commissionShare, fill: '#10b981' },
    { name: 'Self-Stake', value: stats.selfShare, fill: '#6366f1' },
  ];

  const displayReward = () => {
    if (timeframe === 'daily') return stats.daily;
    if (timeframe === 'monthly') return stats.monthly;
    return stats.annual;
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-10">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-emerald-400 text-xs font-bold uppercase tracking-widest mb-2">
            <Activity size={14} />
            <span>Yield Intelligence</span>
          </div>
          <h2 className="text-3xl font-bold text-white">Delegate Revenue Engine</h2>
          <p className="text-gray-400 mt-1 max-w-xl">Project your earnings and analyze network efficiency across different staking scenarios.</p>
        </div>
        
        <div className="flex bg-[#14191f] p-1 rounded-xl border border-gray-800">
          {(['daily', 'monthly', 'annual'] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTimeframe(t)}
              className={`px-4 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                timeframe === t ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-600/20' : 'text-gray-500 hover:text-white'
              }`}
            >
              {t.charAt(0).toUpperCase() + t.slice(1)}
            </button>
          ))}
        </div>
      </header>

      {/* Primary Hero Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="md:col-span-2 bg-gradient-to-br from-emerald-500/20 to-emerald-900/10 border border-emerald-500/30 p-6 rounded-3xl relative overflow-hidden group">
          <div className="absolute -right-4 -top-4 text-emerald-500/10 transition-transform group-hover:scale-110 duration-500">
            <ArrowUpRight size={140} strokeWidth={1} />
          </div>
          <div className="relative z-10">
            <div className="flex items-center space-x-2 text-emerald-400 mb-1">
              <Calendar size={16} />
              <span className="text-xs font-bold uppercase tracking-wider">Projected {timeframe} Revenue</span>
            </div>
            <div className="text-4xl font-black text-white flex items-baseline space-x-2">
              <span>{Math.round(displayReward()).toLocaleString()}</span>
              <span className="text-lg font-medium text-emerald-400/70">IOTX</span>
            </div>
            <p className="text-xs text-emerald-500/60 mt-2 font-medium">Estimated based on 6.0% network APR</p>
          </div>
        </div>

        <div className="bg-[#14191f] border border-gray-800 p-6 rounded-3xl flex flex-col justify-center">
          <div className="flex items-center space-x-2 text-indigo-400 mb-1">
            <Zap size={16} />
            <span className="text-xs font-bold uppercase tracking-wider">Net Voter APY</span>
          </div>
          <div className="text-2xl font-bold text-white">{stats.voterYield.toFixed(2)}%</div>
          <div className="text-[10px] text-gray-500 mt-1">Attractive to outside stakers</div>
        </div>

        <div className="bg-[#14191f] border border-gray-800 p-6 rounded-3xl flex flex-col justify-center">
          <div className="flex items-center space-x-2 text-amber-400 mb-1">
            <PieIcon size={16} />
            <span className="text-xs font-bold uppercase tracking-wider">Monthly Profit</span>
          </div>
          <div className="text-2xl font-bold text-white">{Math.round(stats.monthly).toLocaleString()}</div>
          <div className="text-[10px] text-gray-500 mt-1">Recurring node income</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Controls Panel */}
        <div className="bg-[#14191f] p-8 rounded-3xl border border-gray-800 space-y-8 h-fit shadow-xl">
          <h3 className="text-sm font-bold text-gray-300 flex items-center space-x-2">
            <Settings className="w-4 h-4 text-emerald-500" />
            <span>Node Parameters</span>
          </h3>

          <div className="space-y-6">
            <div className="group">
              <div className="flex justify-between mb-3">
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-widest">Self Stake</label>
                <span className="text-xs font-mono text-emerald-400">{stake.toLocaleString()} IOTX</span>
              </div>
              <input 
                type="range" min="0" max="5000000" step="50000"
                value={stake} onChange={(e) => setStake(Number(e.target.value))}
                className="w-full h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-emerald-500 focus:accent-emerald-400 transition-all"
              />
              <p className="text-[10px] text-gray-600 mt-2 italic">Minimum 1.2M for consensus without endorsement</p>
            </div>
            
            <div className="group">
              <div className="flex justify-between mb-3">
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-widest">Total Endorsements</label>
                <span className="text-xs font-mono text-indigo-400">{voters.toLocaleString()} IOTX</span>
              </div>
              <input 
                type="range" min="0" max="50000000" step="500000"
                value={voters} onChange={(e) => setVoters(Number(e.target.value))}
                className="w-full h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-indigo-500 focus:accent-indigo-400 transition-all"
              />
            </div>

            <div className="group">
              <div className="flex justify-between mb-3">
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-widest">Commission</label>
                <span className="text-xs font-mono text-amber-400">{commission}%</span>
              </div>
              <input 
                type="range" min="0" max="100" step="1"
                value={commission} onChange={(e) => setCommission(Number(e.target.value))}
                className="w-full h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-amber-500 focus:accent-amber-400 transition-all"
              />
            </div>
          </div>

          <div className="pt-6 border-t border-gray-800">
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-bold text-gray-400 uppercase tracking-wider">Revenue Mix</span>
              <span className="text-[10px] text-gray-600">Proportional share</span>
            </div>
            <div className="flex h-3 w-full rounded-full overflow-hidden bg-gray-800">
              <div 
                className="bg-emerald-500 transition-all duration-500" 
                style={{ width: `${(stats.commissionShare / stats.annual) * 100}%` }} 
              />
              <div 
                className="bg-indigo-500 transition-all duration-500" 
                style={{ width: `${(stats.selfShare / stats.annual) * 100}%` }} 
              />
            </div>
            <div className="flex justify-between mt-3">
              <div className="flex items-center space-x-1.5">
                <div className="w-2 h-2 rounded-full bg-emerald-500" />
                <span className="text-[10px] text-gray-400">Commission</span>
              </div>
              <div className="flex items-center space-x-1.5">
                <div className="w-2 h-2 rounded-full bg-indigo-500" />
                <span className="text-[10px] text-gray-400">Self-Stake</span>
              </div>
            </div>
          </div>
        </div>

        {/* Charts Panel */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-[#14191f] p-8 rounded-3xl border border-gray-800 shadow-xl min-h-[400px] flex flex-col">
            <div className="flex items-center justify-between mb-8">
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-400">
                  <TrendingUp size={18} />
                </div>
                <h3 className="font-bold text-white">Cumulative Earnings Projection</h3>
              </div>
              <div className="flex bg-black/30 p-1 rounded-lg">
                <button 
                  onClick={() => setViewMode('projections')}
                  className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${viewMode === 'projections' ? 'bg-gray-700 text-white' : 'text-gray-500'}`}
                >
                  GROWTH
                </button>
                <button 
                  onClick={() => setViewMode('trends')}
                  className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${viewMode === 'trends' ? 'bg-gray-700 text-white' : 'text-gray-500'}`}
                >
                  NETWORK APY
                </button>
              </div>
            </div>

            <div className="flex-1 w-full">
              {viewMode === 'projections' ? (
                <ResponsiveContainer width="100%" height={300}>
                  <AreaChart data={forecastData}>
                    <defs>
                      <linearGradient id="colorCumulative" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1a202c" vertical={false} />
                    <XAxis 
                      dataKey="month" 
                      stroke="#4a5568" 
                      fontSize={11} 
                      tickLine={false} 
                      axisLine={false} 
                    />
                    <YAxis 
                      stroke="#4a5568" 
                      fontSize={11} 
                      tickLine={false} 
                      axisLine={false} 
                      tickFormatter={(val) => `${val / 1000}k`}
                    />
                    <Tooltip 
                      contentStyle={{ backgroundColor: '#0b0e11', border: '1px solid #2d3748', borderRadius: '16px', fontSize: '12px' }}
                      itemStyle={{ color: '#10b981', fontWeight: 'bold' }}
                      labelStyle={{ color: '#94a3b8', marginBottom: '4px' }}
                    />
                    <Area 
                      type="monotone" 
                      dataKey="cumulative" 
                      stroke="#10b981" 
                      strokeWidth={3}
                      fillOpacity={1} 
                      fill="url(#colorCumulative)" 
                      animationDuration={1500}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              ) : (
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={trendData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1a202c" vertical={false} />
                    <XAxis dataKey="date" stroke="#4a5568" fontSize={11} tickLine={false} axisLine={false} />
                    <YAxis 
                      domain={[5, 7]} 
                      stroke="#4a5568" 
                      fontSize={11} 
                      tickLine={false} 
                      axisLine={false} 
                      tickFormatter={(val) => `${val}%`}
                    />
                    <Tooltip 
                      contentStyle={{ backgroundColor: '#0b0e11', border: '1px solid #2d3748', borderRadius: '16px', fontSize: '12px' }}
                      cursor={{ fill: 'rgba(255,255,255,0.05)' }}
                    />
                    <Bar dataKey="apy" fill="#6366f1" radius={[4, 4, 0, 0]} barSize={30}>
                      {trendData.map((_, index) => (
                        <Cell key={`cell-${index}`} fillOpacity={0.4 + (index / trendData.length) * 0.6} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              )}
            </div>

            <div className="mt-6 flex items-center justify-between text-xs text-gray-500 bg-black/20 p-4 rounded-2xl border border-white/5">
              <div className="flex items-center space-x-2">
                <Info size={14} className="text-blue-400" />
                <span>Simulation assumes constant stake and network participation.</span>
              </div>
              <button className="text-emerald-400 hover:text-emerald-300 font-bold uppercase tracking-widest text-[10px]">
                Export Data
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const Settings = (props: any) => (
  <svg 
    {...props} 
    xmlns="http://www.w3.org/2000/svg" 
    width="24" height="24" 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="2" 
    strokeLinecap="round" 
    strokeLinejoin="round"
  >
    <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/>
    <circle cx="12" cy="12" r="3"/>
  </svg>
);

export default RewardCalculator;
